name: Build Windows Forms App

permissions:
  contents: write
  checks: write

  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Configuration to build'
        required: true
        default: 'Release'
        type: choice
        options:
          - 'Release'
          - 'Debug'
      cpu:
        description: 'CPU architecture'
        required: true
        default: 'Any CPU'
        type: choice
        options:
          - 'x64'
          - 'Any CPU'
  release:
    types: [created]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Restore NuGet packages from Cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: ${{ runner.os }}-nuget
    
    - name: Restore build directories from Cache
      id: cache-restore-build
      uses: actions/cache/restore@v4
      with:
        path: |
          src/**/bin
          src/**/obj
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ${{ runner.os }}-build

    - name: Restore dependencies using NuGet
      run: nuget restore

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2


    - if: ${{ github.event_name == 'workflow_dispatch' }}
      name: Build Dispatch
      run: msbuild /p:Configuration="${{ github.event.inputs.build }}" /p:Platform="${{ github.event.inputs.cpu }}"

    - if: ${{ github.event_name == 'workflow_dispatch' }}
      name: Debug tree
      run: tree 

    - if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.cpu != 'Any CPU' }}
      name: Artifacts Upload
      uses: actions/upload-artifact@v5
      with:
        name: art_${{ github.event.inputs.build }}_${{ github.event.inputs.cpu }}
        path: src/YouCast/bin/${{ github.event.inputs.cpu }}/${{ github.event.inputs.build }}/
        if-no-files-found: error

    - if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.cpu == 'Any CPU' }}
      name: Artifacts Upload Any CPU
      uses: actions/upload-artifact@v5
      with:
        name: art_${{ github.event.inputs.build }}_${{ github.event.inputs.cpu }}
        path: src/YouCast/bin/${{ github.event.inputs.build }}/ 
        if-no-files-found: error
      

    - if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Build Release
      run: msbuild -property:Configuration=Release
    
    - if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Archive Release
      run: |
        mkdir -p artifacts
        powershell Compress-Archive -Path src\YouCast\bin\Release\* -DestinationPath artifacts\release.zip
      
    - if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Build x64 Release
      run: msbuild -property:Configuration=Release -property:Platform=x64

    - if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Archive x64 Release
      run: powershell Compress-Archive -Path src\YouCast\bin\x64\Release\* -DestinationPath artifacts\x64_release.zip
    
    - if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Upload x64 Release Assets
      uses: alexellis/upload-assets@0.4.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["artifacts/x64_release.zip", "artifacts/release.zip"]'

    
    - name: Cache NuGet packages
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.nuget/packages
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
    
    - name: Cache build directories
      id: cache-save-build
      uses: actions/cache/save@v4
      with:
        path: |
          src/**/bin
          src/**/obj
        key: ${{ steps.cache-restore-build.outputs.cache-primary-key }}