name: Build Windows Forms App

permissions:
  contents: write
  checks: write

  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

on:
  workflow_dispatch:
  release:
    types: [created]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restore NuGet packages from Cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.nuget/packages
          ~/.local/share/NuGet/Cache
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

    - name: Restore dependencies
      run: nuget restore

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild -property:Configuration=Release

    - if: ${{ github.event_name == 'workflow_dispatch' }}
      name: Artifacts Upload
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: src/YouCast/bin/Release/
        if-no-files-found: error
    
    - if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Archive Release
      run: |
        mkdir -p artifacts
        powershell Compress-Archive -Path src\YouCast\bin\Release\* -DestinationPath artifacts\release.zip

    - if: ${{ github.event_name != 'workflow_dispatch' }}
      name: Upload Release Assets
      uses: alexellis/upload-assets@0.4.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["artifacts/release.zip"]'
    
    - name: Cache NuGet packages
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.nuget/packages
          ~/.local/share/NuGet/Cache
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}