name: Update packages

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'

jobs:
  update:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: install nukeeper
      run: dotnet tool install --global nukeeper

    - name: update packages
      run: nukeeper repo . ${{ github.token }}
